language: csharp
solution: UsefulProteomicsDatabases.sln
install:
  - nuget restore UsefulProteomicsDatabases.sln
  - nuget install NUnit.Console -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=TestAndRelease UsefulProteomicsDatabases.sln 
  - mono ./testrunner/NUnit.ConsoleRunner.*/tools/nunit3-console.exe ./Test/bin/Release/Test.dll
